/**
 * @cond IGNORED_FILES
 *
 * This file is ignored by doxygen
 */
/*
 * This file is subject to the license agreement located in the file LICENSE
 * and cannot be distributed without it. This notice cannot be
 * removed or modified.
 */

#ifdef ENABLE_EXTENSION_PERF

#ifndef __OCR_PERFSTAT_H__
#define __OCR_PERFSTAT_H__

typedef struct _variance_t {
    double var_m;
    double var_s;
} variance_t;

typedef struct _ocrPerfStat {
    u64 average;
    variance_t var;
    u64 current;
} ocrPerfStat_t;

typedef enum _perfEvents {
#ifdef ENABLE_EXTENSION_PERF_KNL
    PERF_HW_CYCLES,           // Total no. of HW cycles taken to execute the EDT
    PERF_HBM_TRAFFIC,         // Amount of HBM traffic generated by this EDT
    PERF_OFFCORE_TRAFFIC,     // Amount of offcore traffic generated by this EDT
#else
    PERF_HW_CYCLES,           // Total no. of HW cycles taken to execute the EDT
    PERF_L1_HITS,             // Total hits to the cache (varies by architecture)
    PERF_L1_MISSES,           // Total hits to the memory (varies by architecture)
    PERF_FLOAT_OPS,           // Total arithmetic floating point ops
#endif
    PERF_HW_MAX,
    /* Software events below */
    PERF_EDT_CREATES = PERF_HW_MAX,  // No. of EDTs created by this EDT
    PERF_DB_TOTAL,                   // Total size of all DBs acquired by this EDT
    PERF_DB_CREATES,                 // Total size of all DBs created by this EDT
    PERF_DB_DESTROYS,                // Total size of all DBs destroyed by this EDT
    PERF_EVT_SATISFIES,              // Total no. of events satisfied by this EDT
    PERF_MAX
} perfEvents;

#ifndef STEADY_STATE_COUNT
#define STEADY_STATE_COUNT 1000000    // How many events are needed to start checking for
#endif                                // steady state conditions; currently very high to
                                      // prevent it from settling down
#ifndef STEADY_STATE_SHIFT
#define STEADY_STATE_SHIFT  4         // Absolute difference is < 6.25% (1/1<<4)
#endif

#define UNINIT_NODE_ID     (u64)(-1)  // Uninitialized node ID
#define NODE_STATS_MAX     0xfffffffffffffff // Default maximum value of per-node statistics
#define STATS_RESET_FREQ   100        // How often should the stats be reset?
#define COUNT_THRESHOLD    10         // How many times should the EDT have run before its
                                      // stats are considered for node counts

typedef struct _ocrPerfCounters {
    void *edt;                        // EDT identified by its function pointer
    ocrPerfStat_t stats[PERF_MAX];    // Performance statistics for each counter
    u32 count;                        // No of samples
    u32 steadyStateMask;              // Mask indicating which counters haven't reached 'steady state'
} ocrPerfCounters_t;

typedef enum _nodePerf {
    NODE_PERF_ALLOC_PRESSURE,       // "Pressure" on the allocator - i.e., sum of active DBs
    NODE_PERF_PROGRESS,             // How many EDTs spawned & events satisfied
    NODE_PERF_LOAD,                 // Sum of HW cycles
    NODE_PERF_FP_LOAD,              // Sum of FP ops
    NODE_PERF_CACHE,                // Sum of cache hits
    NODE_PERF_MEM,                  // Sum of memory accesses
    NODE_PERF_EDTS,                 // Outstanding EDTs
    NODE_PERF_MAX
} nodePerf;

#endif /* __OCR_PERFSTAT_H__ */

#endif /* ENABLE_EXTENSION_PERF */
